"""add_verification_and_reset_columns

Revision ID: a0ef72d9de08
Revises: e35d3ae44fbd
Create Date: 2026-07-07 10:22:17.455349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ef72d9de08'
down_revision: Union[str, Sequence[str], None] = 'e35d3ae44fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_verified = TRUE")
    op.alter_column('users', 'is_verified', nullable=False)
    op.add_column('users', sa.Column('verification_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('verification_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expiry')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'verification_expiry')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
