"""add_voice_metrics_column

Revision ID: c182f0882b0b
Revises: 09af98709466
Create Date: 2026-07-06 11:05:25.441480

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c182f0882b0b'
down_revision: str | Sequence[str] | None = '09af98709466'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_feedbacks', sa.Column('voice_metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_feedbacks', 'voice_metrics')
    # ### end Alembic commands ###
