"""add_coding_platform_tables

Revision ID: ddd786e2f566
Revises: c182f0882b0b
Create Date: 2026-07-06 12:53:39.439475

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ddd786e2f566'
down_revision: str | Sequence[str] | None = 'c182f0882b0b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('default_code', sa.JSON(), nullable=False),
    sa.Column('test_cases_hidden', sa.JSON(), nullable=False),
    sa.Column('test_cases_public', sa.JSON(), nullable=False),
    sa.Column('hints', sa.JSON(), nullable=False),
    sa.Column('optimal_time_complexity', sa.String(length=50), nullable=True),
    sa.Column('optimal_space_complexity', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_questions_id'), 'coding_questions', ['id'], unique=False)
    op.create_index(op.f('ix_coding_questions_slug'), 'coding_questions', ['slug'], unique=True)
    op.create_index(op.f('ix_coding_questions_title'), 'coding_questions', ['title'], unique=False)
    op.create_table('coding_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('code_snapshot', sa.Text(), nullable=True),
    sa.Column('timer_seconds_elapsed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['coding_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_sessions_id'), 'coding_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_coding_sessions_user_id'), 'coding_sessions', ['user_id'], unique=False)
    op.create_table('code_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('is_run', sa.Boolean(), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=True),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('runtime_ms', sa.Float(), nullable=True),
    sa.Column('memory_kb', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['coding_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_submissions_id'), 'code_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_code_submissions_session_id'), 'code_submissions', ['session_id'], unique=False)
    op.create_table('code_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('memory_kb', sa.Float(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=False),
    sa.Column('test_results', sa.JSON(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['code_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_executions_id'), 'code_executions', ['id'], unique=False)
    op.create_table('coding_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('time_complexity', sa.String(length=50), nullable=False),
    sa.Column('space_complexity', sa.String(length=50), nullable=False),
    sa.Column('bugs', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('best_practices', sa.JSON(), nullable=False),
    sa.Column('interview_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['code_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_feedbacks_id'), 'coding_feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coding_feedbacks_id'), table_name='coding_feedbacks')
    op.drop_table('coding_feedbacks')
    op.drop_index(op.f('ix_code_executions_id'), table_name='code_executions')
    op.drop_table('code_executions')
    op.drop_index(op.f('ix_code_submissions_session_id'), table_name='code_submissions')
    op.drop_index(op.f('ix_code_submissions_id'), table_name='code_submissions')
    op.drop_table('code_submissions')
    op.drop_index(op.f('ix_coding_sessions_user_id'), table_name='coding_sessions')
    op.drop_index(op.f('ix_coding_sessions_id'), table_name='coding_sessions')
    op.drop_table('coding_sessions')
    op.drop_index(op.f('ix_coding_questions_title'), table_name='coding_questions')
    op.drop_index(op.f('ix_coding_questions_slug'), table_name='coding_questions')
    op.drop_index(op.f('ix_coding_questions_id'), table_name='coding_questions')
    op.drop_table('coding_questions')
    # ### end Alembic commands ###
